# Generated by Django 5.2.4 on 2025-08-20 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Precipitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('read', models.BooleanField(default=False)),
                ('edit', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubsystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('loa', models.ManyToManyField(blank=True, related_name='users', to='core.loa')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('loa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loa_locations', to='core.loa')),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(auto_now_add=True)),
                ('consequences', models.TextField(blank=True)),
                ('personnel_count', models.IntegerField(default=0)),
                ('technic_count', models.IntegerField(default=0)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_events', to='core.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('loa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loa_events', to='core.loa')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_events', to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='MeasuresTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopted_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_measures', to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('loa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loa_objects', to='core.loa')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_objects', to='core.objecttype')),
            ],
        ),
        migrations.AddField(
            model_name='loa',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_loas', to='core.region'),
        ),
        migrations.CreateModel(
            name='OtherDanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.source')),
            ],
        ),
        migrations.CreateModel(
            name='HydrologicalDanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_name', models.CharField(max_length=255)),
                ('height', models.FloatField()),
                ('description', models.TextField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.source')),
            ],
        ),
        migrations.CreateModel(
            name='GeologicalDanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geography', models.TextField()),
                ('epicenter', models.TextField()),
                ('magnitude', models.IntegerField()),
                ('description', models.TextField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.source')),
            ],
        ),
        migrations.CreateModel(
            name='FireDanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('direction', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.source')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencySituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geography', models.TextField()),
                ('description', models.TextField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.source')),
            ],
        ),
        migrations.CreateModel(
            name='AdverseWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geography', models.TextField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('wind', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.condition')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('precipitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.precipitation')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.source')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsystem_info', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('influenced_objects', models.ManyToManyField(blank=True, related_name='influenced_by_failures', to='core.object')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.object')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subsystem')),
                ('subsystem_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subsystemstatus')),
            ],
        ),
        migrations.AddField(
            model_name='subsystem',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsystems', to='core.system'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_attachments', to='core.event')),
            ],
            options={
                'indexes': [models.Index(fields=['author'], name='core_attach_author__d05755_idx'), models.Index(fields=['-created_at'], name='core_attach_created_001bfc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['begin'], name='core_event_begin_77b3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['loa', 'category'], name='core_event_loa_id_5e099d_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['location'], name='core_event_locatio_529947_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['end'], name='core_event_end_6d867a_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['loa'], name='core_locati_loa_id_8919d2_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_type'], name='core_locati_locatio_552496_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='core_locati_name_65ac84_idx'),
        ),
        migrations.AddIndex(
            model_name='measurestaken',
            index=models.Index(fields=['adopted_at'], name='core_measur_adopted_3875d5_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['loa'], name='core_object_loa_id_d7ad51_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['object_type'], name='core_object_object__95a3a4_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['name'], name='core_object_name_ed66cf_idx'),
        ),
        migrations.AddIndex(
            model_name='otherdanger',
            index=models.Index(fields=['event'], name='core_otherd_event_i_950ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='otherdanger',
            index=models.Index(fields=['source'], name='core_otherd_source__2291da_idx'),
        ),
        migrations.AddIndex(
            model_name='hydrologicaldanger',
            index=models.Index(fields=['event'], name='core_hydrol_event_i_f95290_idx'),
        ),
        migrations.AddIndex(
            model_name='hydrologicaldanger',
            index=models.Index(fields=['source'], name='core_hydrol_source__73bde6_idx'),
        ),
        migrations.AddIndex(
            model_name='geologicaldanger',
            index=models.Index(fields=['event'], name='core_geolog_event_i_9c6ced_idx'),
        ),
        migrations.AddIndex(
            model_name='geologicaldanger',
            index=models.Index(fields=['source'], name='core_geolog_source__44d895_idx'),
        ),
        migrations.AddIndex(
            model_name='firedanger',
            index=models.Index(fields=['event'], name='core_fireda_event_i_23440d_idx'),
        ),
        migrations.AddIndex(
            model_name='firedanger',
            index=models.Index(fields=['source'], name='core_fireda_source__ff3e47_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencysituation',
            index=models.Index(fields=['event'], name='core_emerge_event_i_0e55ae_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencysituation',
            index=models.Index(fields=['source'], name='core_emerge_source__f08863_idx'),
        ),
        migrations.AddIndex(
            model_name='adverseweather',
            index=models.Index(fields=['event'], name='core_advers_event_i_534802_idx'),
        ),
        migrations.AddIndex(
            model_name='adverseweather',
            index=models.Index(fields=['source'], name='core_advers_source__260d00_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentfailure',
            index=models.Index(fields=['object'], name='core_equipm_object__5db0cb_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentfailure',
            index=models.Index(fields=['event'], name='core_equipm_event_i_972938_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentfailure',
            index=models.Index(fields=['subsystem_status'], name='core_equipm_subsyst_eb321d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentfailure',
            index=models.Index(fields=['subsystem', 'subsystem_status'], name='core_equipm_subsyst_60c37b_idx'),
        ),
    ]
