# Generated by Django 5.2.4 on 2025-08-08 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_attachment_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurestaken',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_measures', to='core.event'),
        ),
    ]
