# Generated by Django 5.2.4 on 2025-08-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_attachment_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='measurestaken',
            name='core_measur_event_i_013b91_idx',
        ),
        migrations.RemoveField(
            model_name='measurestaken',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='measures',
            field=models.ManyToManyField(blank=True, related_name='measure_events', to='core.measurestaken'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='core_locati_name_65ac84_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['name'], name='core_object_name_ed66cf_idx'),
        ),
    ]
