# Generated by Django 5.2.4 on 2025-08-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_measurestaken_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseweather',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adverseweather',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adverseweather',
            name='wind',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
