# Generated by Django 5.2.4 on 2025-08-09 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_adverseweather_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseweather',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event', unique=True),
        ),
    ]
