# Generated by Django 5.2.4 on 2025-08-09 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_adverseweather_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseweather',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
        migrations.AlterField(
            model_name='equipmentfailure',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
    ]
