# Generated by Django 5.2.4 on 2025-08-09 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_adverseweather_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencysituation',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
        migrations.AlterField(
            model_name='firedanger',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
        migrations.AlterField(
            model_name='geologicaldanger',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
        migrations.AlterField(
            model_name='hydrologicaldanger',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
        migrations.AlterField(
            model_name='otherdanger',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
    ]
