# Generated by Django 5.2.4 on 2025-08-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_emergencysituation_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentfailure',
            name='additional_info',
        ),
        migrations.AlterField(
            model_name='equipmentfailure',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='consequences',
            field=models.TextField(blank=True),
        ),
    ]
